package com.customitem.engine;

import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.inventory.ItemStack;

import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Handles custom ore drops from surrogate deepslate blocks generated by OrePopulator.
 * Supports Fortune yield multiplication and Silk Touch raw-block drops.
 */
public final class OreBreakListener implements Listener {

    private final CustomItemEngine plugin;
    private final Random random = ThreadLocalRandom.current();

    public OreBreakListener(CustomItemEngine plugin) {
        this.plugin = plugin;
    }

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onBreak(BlockBreakEvent event) {
        Block block = event.getBlock();
        // Only handle our surrogate ore blocks.
        if (block.getType() != Material.DEEPSLATE_DIAMOND_ORE) return;

        Player player = event.getPlayer();
        ItemStack tool = player.getInventory().getItemInMainHand();
        boolean silkTouch = tool.containsEnchantment(Enchantment.SILK_TOUCH);
        int fortuneLevel = tool.getEnchantmentLevel(Enchantment.FORTUNE);

        // Cancel default diamond drop.
        event.setDropItems(false);

        // Determine which custom ore to drop. With a single surrogate we drop
        // the first enabled ore item; could be extended per-chunk metadata.
        String dropId = pickOreItemId();
        if (dropId == null) return;

        ItemStack customDrop = plugin.getItemRegistry().build(dropId);
        if (customDrop == null) return;

        ConfigurationSection oreSec = plugin.getItemRegistry().get(dropId).section
                .getConfigurationSection("ore");
        int min = oreSec != null ? oreSec.getInt("drop-min", 1) : 1;
        int max = oreSec != null ? oreSec.getInt("drop-max", 2) : 2;
        boolean fortuneMult = oreSec == null || oreSec.getBoolean("fortune-multiplier", true);
        boolean silkDrop = oreSec != null && oreSec.getBoolean("silk-touch-drop", true);

        if (silkTouch && silkTouch) {
            // Silk touch yields one raw ore item.
            customDrop.setAmount(1);
            block.getWorld().dropItemNaturally(block.getLocation(), customDrop);
            return;
        }

        int amount = min + random.nextInt(Math.max(1, max - min + 1));
        if (fortuneMult && fortuneLevel > 0) {
            amount *= (1 + random.nextInt(fortuneLevel + 1));
        }
        customDrop.setAmount(Math.max(1, amount));
        block.getWorld().dropItemNaturally(block.getLocation(), customDrop);
    }

    private String pickOreItemId() {
        for (String id : plugin.getItemRegistry().all().keySet()) {
            ConfigurationSection sec = plugin.getItemRegistry().get(id).section;
            ConfigurationSection oreSec = sec.getConfigurationSection("ore");
            if (oreSec != null && oreSec.getBoolean("enabled", true)) {
                return id;
            }
        }
        return null;
    }
}
